spring.application.name=ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger
spring.datasource.username=ledger_user
spring.datasource.password=ledger_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=ledger

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=ledger
spring.flyway.default-schema=ledger

spring.threads.virtual.enabled=true

spring.jackson.time-zone=UTC

server.error.include-message=never
server.error.include-stacktrace=never

server.port=8080